#!/bin/bash


extract() {
    if [ "$#" -eq 0 ]; then
        echo "Usage:    extract <filename>"
        exit 1

    elif [ -f "$1" ]; then
        case "$1" in
            *.zip)                   unzip   "$1"   ;;
            *.rar)                   rar x   "$1"   ;;
            *.tar)                   tar xf  "$1"   ;;
            *.tar.gz)                tar xzf "$1"   ;;
            *.tar.bz2)               tar xjf "$1"   ;;
            *.bz2)                   bunzip2 "$1"   ;;
            *.tgz)                   tar xzf "$1"   ;;
            *.tar.xz)                tar xvf "$1"   ;;
            *.7z)		     7z x    "$1"   ;;
            *)     echo "Unsported file type '$1'"  ;;
        esac
    fi
}

extract  "$@"
